SELECT ANIMAL_ID, NAME
FROM (
    SELECT o.ANIMAL_ID, o.NAME, ROW_NUMBER() OVER(ORDER BY o.DATETIME - i.DATETIME DESC) AS RN
    FROM ANIMAL_OUTS o
    JOIN ANIMAL_INS i
    ON o.animal_id = i.animal_id
)
WHERE RN < 3
ORDER BY RN;