WITH HOST_COUNT as(SELECT HOST_ID
        FROM PLACES
        GROUP BY HOST_ID
        HAVING COUNT(*) > 1
)

SELECT p.ID, p.NAME, p.HOST_ID
FROM PLACES p
    JOIN HOST_COUNT c
    ON p.HOST_ID = c.HOST_ID
ORDER BY p.ID;