WITH TMP AS (
    SELECT H.HISTORY_ID
        , C.CAR_TYPE
        , C.DAILY_FEE
        , (CASE 
            WHEN (H.END_DATE - H.START_DATE)+1 < 7 THEN NULL
            WHEN (H.END_DATE - H.START_DATE)+1 < 30 THEN '7일 이상'
            WHEN (H.END_DATE - H.START_DATE)+1 < 90 THEN '30일 이상'
            ELSE '90일 이상' END 
        ) DISCOUNT_TYPE
        , (H.END_DATE - H.START_DATE)+1 PERIOD
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT T.HISTORY_ID
    , TRUNC((T.DAILY_FEE * PERIOD) / 100 * (100 - NVL(P.DISCOUNT_RATE,0))) FEE
FROM TMP T
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON T.DISCOUNT_TYPE = P.DURATION_TYPE
    AND T.CAR_TYPE = P.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC