SELECT B.TIME, NVL(COUNT(A.ANIMAL_ID), 0)
FROM ANIMAL_OUTS A 
RIGHT OUTER JOIN (SELECT LEVEL-1 TIME FROM DUAL CONNECT BY LEVEL-1 < 24) B
ON B.TIME = TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24'))
GROUP BY B.TIME
ORDER BY 1;